In [2]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import math

In [75]:
n = 1
num_samples = 6
MU_0 = 0
MU_1 = 1
SIGMA = 1

In [76]:
def generate_time_series(MU_0, MU_1, SIGMA, N, NUM_SAMPLES):
    NUM_SAMPLES = int(NUM_SAMPLES / 2)
    TS = np.concatenate(( np.random.normal(MU_0,SIGMA,(1, NUM_SAMPLES * N)), 
                     np.random.normal(MU_1,SIGMA,(1, NUM_SAMPLES * N))),axis=1 )
    return TS[0]

In [77]:
TS = generate_time_series(0, 1, 1, n, num_samples)

In [80]:
x_bar = (1/(num_samples * 2)) * np.sum(TS)

x_bar_k = []
x_bar_n_minus_k = []

for k in range(0, TS.shape[0]-1):
    x_bar_k.append(np.sum(TS[:k+1])/(k+1))
    x_bar_n_minus_k.append(np.sum(TS[k+1:])/(num_samples - (k+1)))
    
x_bar_k = np.array(x_bar_k)
x_bar_n_minus_k = np.array(x_bar_n_minus_k)

In [81]:
print(TS)
print(x_bar_k)
print(x_bar_n_minus_k)

[ 2.02453933 -1.55305149  1.39890214  0.40382461  2.0217927   0.84617751]
[ 2.02453933  0.23574392  0.62346333  0.56855365  0.85920146]
[ 0.62352909  1.16767424  1.09059827  1.4339851   0.84617751]


### Calculate sk.  (confusing)

In [83]:
sk = []
for k in range(0, x_bar_k.shape[0]):
    left = np.sum(np.power((TS[:k+1] - x_bar_k[k]), 2))
    right = np.sum(np.power((TS[k+1:] - x_bar_k[k]), 2))
    sk.append(left + right)
    
sk = np.array(sk)

In [84]:
sk

array([ 17.2058383 ,  11.34336558,   9.35470386,   9.52669568,   9.02740954])