In [2]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot as plt
import math

In [3]:
n = 1
num_samples = 6
MU_0 = 0
MU_1 = 1
SIGMA = 1

In [4]:
def generate_time_series(MU_0, MU_1, SIGMA, N, NUM_SAMPLES):
    NUM_SAMPLES = int(NUM_SAMPLES / 2)
    TS = np.concatenate(( np.random.normal(MU_0,SIGMA,(1, NUM_SAMPLES * N)), 
                     np.random.normal(MU_1,SIGMA,(1, NUM_SAMPLES * N))),axis=1 )
    return TS[0]

In [5]:
TS = generate_time_series(0, 1, 1, n, num_samples)

In [6]:
x_bar = (1/(num_samples * 2)) * np.sum(TS)

x_bar_k = []
x_bar_n_minus_k = []

for k in range(0, TS.shape[0]-1):
    x_bar_k.append(np.sum(TS[:k+1])/(k+1))
    x_bar_n_minus_k.append(np.sum(TS[k+1:])/(num_samples - (k+1)))
    
x_bar_k = np.array(x_bar_k)
x_bar_n_minus_k = np.array(x_bar_n_minus_k)

In [7]:
print(TS)
print(x_bar_k)
print(x_bar_n_minus_k)

[ 0.69189698  0.81280724  1.00591417  0.32288438 -0.05940627  0.47197408]
[ 0.69189698  0.75235211  0.8368728   0.70837569  0.5548193 ]
[ 0.51083472  0.43534159  0.24515073  0.2062839   0.47197408]


### Calculate sk.  (confusing)

In [8]:
sk = []
for k in range(0, x_bar_k.shape[0]):
    left = np.sum(np.power((TS[:k+1] - x_bar_k[k]), 2))
    right = np.sum(np.power((TS[k+1:] - x_bar_k[k]), 2))
    sk.append(left + right)
    
sk = np.array(sk)

In [9]:
sk

array([ 0.86221904,  0.99360941,  1.25082346,  0.89368506,  0.72676484])

In [11]:
vk = []

for k in range(0, x_bar_k.shape[0]):
    left  = k*(x_bar_k[k] - x_bar)**2
    right = (num_samples - k) * ((x_bar_n_minus_k[k] - x_bar)**2)
    vk.append(left + right)
    
vk = np.array(vk)

In [13]:
np.argmax(vk)

2

In [14]:
vk[2]

0.6441144999980527

In [15]:
vk

array([ 0.3465477 ,  0.36802984,  0.6441145 ,  0.5875633 ,  0.40451535])